services:
    app:
        extends:
            file: docker-compose.yml
            service: app
        ports:
            - "8000:8000"
        command: npm run dev
        volumes:
            - "./app:/app"
        build:
            dockerfile: Dockerfile
    caddy:
        image: caddy
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - "./services/caddy:/config"
        depends_on: [app]
