services:
    app:
        extends:
            file: docker-compose.yml
            service: app
        ports:
            - "8000:8000"
        command: npm run dev
        volumes:
            - "./app:/app"
        build:
            dockerfile: Dockerfile
