services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile.production
        command: npm test
        image: sagser/devops-for-programmers-project-74
        depends_on: [db]
    
    db:
        image: postgres
        environment:
            POSTGRES_USER: "${DATABASE_USERNAME}"
            POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
