services:
    app:
        ports:
            - "8000:8000"
        command: ["bash", "-c", "sleep 3 && npm start"]
        volumes:
            - "./app:/app"
        build:
            context: .
            dockerfile: Dockerfile
    caddy:
        image: caddy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - "./services/caddy:/config"
        depends_on: [app]
